version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npx ng build --configuration production

artifacts:
  base-directory: dist
  files:
    - '**/*'
